In [1]:
import matplotlib.pyplot as plt
import requests
import pandas as pd
import scipy.stats as st
import googlemaps

import time
from us import states
from scipy.stats import linregress
import numpy as np
import re
import csv

# Reference the file where the CSV is located
tweet_data = "trumpTweets.csv"

# Import the data into a Pandas DataFrame
trump_df = pd.read_csv(tweet_data)
trump_df.head()

,Unnamed: 0,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,Year,Hour
0,0,Twitter for iPhone,Our prayers are with the families of the victi...,12-31-2019 00:57:13,39706,191167,False,1211813523581546496,2019,12 AM to 4 AM
1,1,Twitter for iPhone,RT @realDonaldTrump: https://t.co/Mn4EJ7Jbh8,12-31-2019 00:00:34,40917,0,True,1211799266974478337,2019,12 AM to 4 AM
2,2,Twitter for iPhone,RT @BreitbartNews: This Christmas let the impe...,12-30-2019 22:23:36,6012,0,True,1211774864362737665,2019,8 PM to 12 AM
3,3,Twitter for iPhone,He is Fake News will always be Fredo to us. I ...,12-30-2019 22:23:04,20037,81302,False,1211774730258264066,2019,8 PM to 12 AM
4,4,Twitter for iPhone,Thank you to highly respected Jewish leader Do...,12-30-2019 14:28:26,21588,112303,False,1211655287247126535,2019,12 PM to 4 PM

In [92]:
"12 AM to 4 AM" = trump_df.loc[(trump_df["created_at"] > 0)&(trump_df["created_at"] < 4), trump_df["Hour"]]

SyntaxError: can't assign to literal (<ipython-input-92-1c041de3fed0>, line 1)

In [54]:
trump_df["created_at"][0].split(' ')[1].split(':')[0]
#> 0)&(trump_df["created_at"] < 4)]

'00'

In [7]:
trump_df["Month"]  = trump_df["created_at"].astype(str).str.split('-').str.get(0).str.split(" ").str.get(0)

In [2]:
trump_df.head()

,Unnamed: 0,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,Year,Hour
0,0,Twitter for iPhone,Our prayers are with the families of the victi...,12-31-2019 00:57:13,39706,191167,False,1211813523581546496,2019,12 AM to 4 AM
1,1,Twitter for iPhone,RT @realDonaldTrump: https://t.co/Mn4EJ7Jbh8,12-31-2019 00:00:34,40917,0,True,1211799266974478337,2019,12 AM to 4 AM
2,2,Twitter for iPhone,RT @BreitbartNews: This Christmas let the impe...,12-30-2019 22:23:36,6012,0,True,1211774864362737665,2019,8 PM to 12 AM
3,3,Twitter for iPhone,He is Fake News will always be Fredo to us. I ...,12-30-2019 22:23:04,20037,81302,False,1211774730258264066,2019,8 PM to 12 AM
4,4,Twitter for iPhone,Thank you to highly respected Jewish leader Do...,12-30-2019 14:28:26,21588,112303,False,1211655287247126535,2019,12 PM to 4 PM

In [103]:
trump_df.loc[(trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) < 4) ,"Hour"] = "12 AM to 4 AM"

In [104]:
trump_df.loc[(trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) < 8 )  & (trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) >= 4) ,"Hour"] = "4 AM to 8 AM"

In [97]:
trump_df.loc[(trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) < 12 )  & (trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) >= 8) ,"Hour"] = "8 AM to 12 PM"

In [98]:
trump_df.loc[(trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) < 16 )  & (trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) >= 12) ,"Hour"] = "12 PM to 4 PM"

In [99]:
trump_df.loc[(trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) < 20 )  & (trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) >= 16) ,"Hour"] = "4 PM to 8 PM"

In [100]:
trump_df.loc[(trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) < 24 )  & (trump_df["created_at"].astype(str).str.split(' ').str.get(1).str.split(':').str.get(0).astype(int) >= 20) ,"Hour"] = "8 PM to 12 AM"

In [108]:
trump_df['Hour'].unique()

array(['12 AM to 4 AM', '8 PM to 12 AM', '12 PM to 4 PM', '4 PM to 8 PM',
       '4 AM to 8 AM', '8 AM to 12 PM'], dtype=object)

In [7]:
!pip install wordcloud

Collecting wordcloud
  Downloading https://files.pythonhosted.org/packages/65/41/abefdda082c7b211248e412fb2c7a8dc69d474f18ed61a5a784f20f73bb7/wordcloud-1.7.0-cp37-cp37m-win_amd64.whl (157kB)
Requirement already satisfied: matplotlib in c:\users\clayt\anaconda3\lib\site-packages (from wordcloud) (3.1.1)
Requirement already satisfied: pillow in c:\users\clayt\anaconda3\lib\site-packages (from wordcloud) (6.2.0)
Requirement already satisfied: numpy>=1.6.1 in c:\users\clayt\anaconda3\lib\site-packages (from wordcloud) (1.16.5)
Requirement already satisfied: cycler>=0.10 in c:\users\clayt\anaconda3\lib\site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\clayt\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\clayt\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.4.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\clayt\appdata\roaming\python\python37\site-packages (from matplotlib->wordcloud) (2.8.1)
Requirement already satisfied: six in c:\users\clayt\appdata\roaming\python\python37\site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.14.0)
Requirement already satisfied: setuptools in c:\users\clayt\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->wordcloud) (41.4.0)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.7.0

In [9]:
trump_df.to_csv('trumpTime.csv')

In [37]:
len(my_list)

13871

mylist

In [35]:
from collections import Counter
import re

counts = Counter()
words = re.compile(r'\w+')

for sentence in my_list:
    counts.update(words.findall(sentence.lower()))

In [36]:
counts

Counter({'our': 2751,
         'prayers': 65,
         'are': 2869,
         'with': 2768,
         'the': 18119,
         'families': 122,
         'of': 7222,
         'victims': 47,
         'and': 8686,
         'congregation': 1,
         'yesterday': 153,
         's': 2832,
         'church': 7,
         'attack': 88,
         'it': 2709,
         'was': 1828,
         'over': 451,
         'in': 5332,
         '6': 70,
         'seconds': 3,
         'thanks': 99,
         'to': 9395,
         'brave': 65,
         'parishioners': 1,
         'who': 1066,
         'acted': 7,
         'protect': 128,
         '242': 2,
         'fellow': 16,
         'worshippers': 1,
         'lives': 95,
         'were': 469,
         'saved': 32,
         'by': 1406,
         'these': 274,
         'heroes': 62,
         'texas': 119,
         'laws': 116,
         'allowing': 27,
         'them': 464,
         'carry': 6,
         'arms': 16,
         'rt': 3788,
         'realdonaldtrump': 1052,
         'https': 4325,
         't': 5979,
         'co': 4317,
         'mn4ej7jbh8': 2,
         'breitbartnews': 26,
         'this': 1991,
         'christmas': 36,
         'let': 223,
         'impeach': 94,
         'a': 6365,
         'maniacs': 1,
         'your': 558,
         'life': 119,
         'know': 326,
         'we': 2522,
         're': 222,
         'lauging': 1,
         'at': 1695,
         'not': 1524,
         'tnn69dbom': 1,
         'he': 1575,
         'is': 5179,
         'fake': 813,
         'news': 936,
         'will': 2692,
         'always': 214,
         'be': 2529,
         'fredo': 8,
         'us': 413,
         'i': 3171,
         'should': 623,
         'release': 58,
         'some': 249,
         'his': 865,
         'dishonest': 89,
         'interviews': 17,
         'coupled': 2,
         'bad': 402,
         'ratings': 107,
         'd': 158,
         'out': 810,
         'eek6pdsrnv': 1,
         'thank': 920,
         'you': 2140,
         'highly': 104,
         'respected': 78,
         'jewish': 17,
         'leader': 70,
         'dov': 2,
         'hikind': 2,
         'for': 4208,
         'wonderful': 188,
         'statements': 39,
         'about': 813,
         'me': 687,
         'morning': 109,
         'on': 3284,
         'foxandfriends': 280,
         'anti': 69,
         'semitic': 6,
         'monsey': 1,
         'new': 788,
         'york': 178,
         '7th': 9,
         'night': 207,
         'hanukkah': 6,
         'last': 321,
         'horrific': 14,
         'must': 480,
         'all': 1541,
         'come': 231,
         'together': 219,
         'fight': 132,
         'confront': 9,
         'eradicate': 5,
         'evil': 19,
         'scourge': 4,
         'semitism': 8,
         'melania': 95,
         'wish': 32,
         'quick': 11,
         'full': 169,
         'recovery': 26,
         'crazy': 114,
         'nancy': 196,
         'pelosi': 261,
         'spend': 29,
         'more': 905,
         'time': 699,
         'her': 304,
         'decaying': 2,
         'city': 62,
         'less': 62,
         'impeachment': 453,
         'hoax': 163,
         'enozzfxxmg': 2,
         'any': 302,
         'answers': 19,
         'cbb9tlxiue': 1,
         'california': 108,
         'do': 954,
         'something': 124,
         'their': 972,
         'tremendous': 140,
         'homeless': 13,
         'problems': 39,
         'they': 2283,
         'setting': 40,
         'records': 56,
         'if': 697,
         'spirit': 34,
         'xlqr9vx1xo': 1,
         'danscavino': 54,
         'trumppence2020': 1,
         'kag': 17,
         'kyiwu22rsn': 1,
         'joe': 131,
         'so': 1218,
         'good': 573,
         'workers': 120,
         'gbcqf88i6j': 1,
         'juliereichwein1': 1,
         'mother': 8,
         'six': 28,
         'killed': 53,
         'illegal': 235,
         'alien': 5,
         'previously': 8,
         'deported': 8,
         'times': 169,
         'sanctuary': 46,
         'denver': 2,
         'then': 181,
         'flees': 1,
         'sc': 12,
         'realbasedmaga': 1,
         'rush': 22,
         'limbaugh': 12,
         'media': 593,
         'flooding': 23,
         'w': 158,
         'negativity': 1,
         'abt': 2,
         'trump': 1279,
         'order': 142,
         'make': 472,
         'have': 2138,
         'doubts': 5,
         'publicity': 3,
         'af': 1,
         'juliet': 1,
         '61k4wtgtsp': 1,
         'adrianacohen16': 1,
         'ignore': 5,
         'called': 172,
         'experts': 22,
         'keep': 195,
         'getting': 236,
         'wrong': 189,
         'a1idt0cro0': 1,
         'foxbusiness': 41,
         'economy': 317,
         'dirty': 34,
         'cop': 11,
         'highest': 110,
         'level': 102,
         'scum': 3,
         '9t2qetqgcl': 1,
         'adriana': 1,
         'zxqhx55px5': 1,
         'sad': 88,
         'see': 363,
         'that': 3196,
         'state': 418,
         'falling': 10,
         'apart': 18,
         'want': 588,
         'investigate': 45,
         'hate': 65,
         'even': 521,
         'than': 687,
         'governor': 224,
         'cuomo': 29,
         'has': 1624,
         'lost': 130,
         'control': 69,
         'mind': 20,
         'very': 1270,
         'support': 230,
         'given': 94,
         'america': 720,
         'great': 2536,
         'again': 442,
         'movement': 27,
         'agenda': 81,
         'major': 115,
         'star': 39,
         'never': 675,
         'wavered': 3,
         'despite': 140,
         'hits': 39,
         'had': 448,
         'endure': 9,
         'voice': 18,
         'far': 290,
         'bigger': 53,
         'theirs': 2,
         'governors': 14,
         'can': 632,
         'handle': 12,
         'situation': 44,
         'which': 504,
         'able': 70,
         'easily': 44,
         'call': 250,
         'politely': 3,
         'ask': 68,
         'help': 248,
         'would': 702,
         'easy': 60,
         'competence': 1,
         'wow': 130,
         'what': 770,
         'going': 455,
         'big': 832,
         'stuff': 28,
         'hohserkgh9': 2,
         'surfermom77': 1,
         'rep': 78,
         'ratcliffe': 11,
         'suggested': 12,
         'monday': 35,
         'whistleblower': 138,
         'eric': 21,
         'ciaramella': 1,
         'committed': 63,
         'perjury': 4,
         'making': 191,
         'false': 165,
         'h': 85,
         'annaapp91838450': 2,
         'patriotsbadazzfollowersmaga': 1,
         'runaway': 1,
         'fightfor': 1,
         'godjusticepresidenttrump': 1,
         'trumpladyfran': 1,
         'sweet': 3,
         'anna': 4,
         'amp': 2050,
         'potus': 158,
         'needs': 58,
         'those': 215,
         'close': 105,
         'himthat': 1,
         'trust': 21,
         'deep': 37,
         'statewantin': 1,
         'wall': 367,
         'funded': 15,
         'being': 506,
         'built': 87,
         '84boxkr2eo': 1,
         'now': 1040,
         'wasn': 63,
         'nice': 89,
         'rherigdeqo': 1,
         'ceebeesheart': 1,
         'plus': 59,
         '10': 85,
         'get': 736,
         'trying': 160,
         'follow': 34,
         'like': 465,
         'maze': 2,
         'no': 1261,
         'sense': 22,
         'direction': 14,
         'don': 539,
         'forget': 56,
         'rudygiuliani': 21,
         'accounts': 10,
         'chamber': 5,
         'ukraine': 149,
         'found': 58,
         'an': 792,
         'alleged': 9,
         'misuse': 2,
         '5': 111,
         '3b': 1,
         'u': 787,
         'funds': 7,
         'during': 148,
         'obama': 323,
         'administration': 253,
         'while': 207,
         'bide': 1,
         'alexmjordan': 1,
         'jordansviewexpress': 1,
         '283': 1,
         'best': 260,
         'yet': 130,
         'feeling': 8,
         'hitch': 1,
         'ride': 6,
         'train': 19,
         'featuring': 1,
         'jon': 14,
         'voight': 1,
         'fra': 1,
         'just': 1076,
         'doesn': 175,
         'seem': 21,
         'right': 259,
         '0fmqj79dlx': 1,
         'sjpfish': 10,
         'hey': 6,
         'world': 334,
         'leaders': 115,
         'asking': 56,
         'how': 366,
         'mimic': 1,
         'done': 492,
         '9mmcassy': 6,
         'etheelephant1': 1,
         'first': 419,
         'lady': 47,
         'she': 322,
         'really': 300,
         'cares': 13,
         'l4q3p0mghi': 1,
         'congresswoman': 16,
         'lesko': 2,
         'american': 624,
         'ey3hxfvlqo': 1,
         'americans': 225,
         'president': 1634,
         'briteeye777': 2,
         'ki4fdw': 1,
         'patti_sc60': 1,
         'kag1776maga': 1,
         'inblondwetrust': 2,
         'gre': 2,
         'reasons': 27,
         'vote': 459,
         'democratic': 43,
         'shipmate68': 1,
         'fortressfin': 1,
         'tagruber': 1,
         'christophercsa6': 1,
         'secretstranger9': 2,
         'mmch': 1,
         'fired': 83,
         'up': 738,
         'serremmy': 1,
         'rl9631': 1,
         'racysicilian': 2,
         'sealeygerald': 1,
         'marianahirmas': 2,
         'markkirin_': 1,
         'home': 119,
         'depot': 3,
         'founder': 6,
         'slams': 9,
         'dem': 65,
         'candidates': 30,
         'claiming': 8,
         'millionaires': 1,
         'didn': 222,
         'work': 322,
         'pjbo': 1,
         'ag': 23,
         'bill': 208,
         'barr': 39,
         'nypd': 8,
         'only': 465,
         'ny': 5,
         'finest': 20,
         'countries': 216,
         'ann': 4,
         'anna_deardorff': 1,
         'mjgranger1': 2,
         'israel_advocacy': 2,
         'amerwn77': 2,
         'leezeldin': 2,
         'repleezeldin': 32,
         'rashidatlaib': 3,
         'yes': 32,
         'but': 961,
         'rogue': 12,
         'isn': 67,
         'message': 32,
         'violation': 20,
         'hous': 2,
         'true': 187,
         'democrat': 301,
         'party': 269,
         'vqzseg0vpg': 1,
         'america1sttiger': 1,
         'case': 148,
         'forgot': 7,
         'joebiden': 7,
         'here': 209,
         'admitting': 8,
         'crime': 367,
         'correction': 3,
         'bragging': 3,
         'rea': 2,
         'tweekerhateme': 2,
         '328': 1,
         'my_trigger11': 1,
         'mikemaga2020': 1,
         'lpmitchellrtr': 1,
         'skeeter19592': 1,
         'godfamilyjesus': 1,
         'jame': 1,
         'calineedshelp': 1,
         'already': 155,
         'why': 393,
         'look': 294,
         'around': 107,
         'agree': 73,
         'join': 106,
         'patriots': 36,
         'unite': 5,
         'without': 126,
         'commenting': 1,
         'reply': 2,
         'debport03755076': 1,
         'ofbxp4lpdp': 1,
         'kind': 52,
         'animal': 9,
         'oqsexxixdv': 1,
         'hillary': 259,
         'give': 164,
         'another': 203,
         'try': 69,
         'wisconsin': 43,
         'pennsylvania': 91,
         'michigan': 52,
         'north': 307,
         'carolina': 131,
         'others': 216,
         'ultsbv16c5': 1,
         'rohll5': 2,
         'winning': 93,
         'kag2020why': 1,
         'long': 276,
         'faces': 4,
         'msnbc': 45,
         'got': 256,
         'nykr59': 1,
         'two': 299,
         'possibilities': 1,
         'wiretapping': 1,
         'neither': 22,
         'goodby': 1,
         'frank': 5,
         'watt': 1,
         'report': 289,
         'g': 92,
         'findings': 10,
         'use': 106,
         'fis': 1,
         'emha3d8ojx': 1,
         'john_kissmybot': 1,
         'anyone': 92,
         'afraid': 16,
         'michael': 80,
         'moore': 23,
         'wants': 120,
         'because': 432,
         'voted': 68,
         'skusbddww1': 1,
         'made': 397,
         'same': 151,
         'prediction': 2,
         '2016': 129,
         'nobody': 46,
         'ever': 387,
         'said': 371,
         'stupid': 21,
         'xdezsts1pt': 1,
         'petluvers4trump': 1,
         'chuck': 81,
         'senschumer': 6,
         'confident': 6,
         'did': 369,
         'won': 206,
         'repadamschiff': 25,
         'bmcadory9': 1,
         'leading': 39,
         'democrats': 1183,
         '2020': 142,
         'presidential': 150,
         'election': 404,
         'according': 26,
         'usatoday': 4,
         'suffolk_u': 1,
         'blame': 22,
         'b2cwtpd4fz': 1,
         'lrihendry': 6,
         'fbi': 367,
         'hide': 14,
         'lies': 71,
         'bleach': 1,
         'bit': 12,
         'emails': 58,
         'blackberry': 1,
         'devices': 3,
         'hiding': 9,
         'keeping': 38,
         'among': 34,
         'oann': 30,
         'doing': 468,
         'incredible': 162,
         'reporting': 84,
         'lamestream': 23,
         'respect': 71,
         'back': 486,
         'low': 126,
         'imi4a0dx4f': 1,
         'text88022': 1,
         'siri': 4,
         'united': 535,
         'states': 514,
         '9rrui5sw1h': 1,
         'chicago1ray': 1,
         'need': 262,
         'jobs': 439,
         'denzelwashington': 1,
         'looks': 62,
         'ethnicity': 1,
         'sheriffc': 1,
         'hoosiers1986': 1,
         'speakerpelosi': 18,
         'facts': 93,
         'clear': 53,
         'led': 47,
         'based': 110,
         '2nd': 78,
         '3rd': 8,
         '4th': 17,
         'hand': 52,
         'geraldorivera': 19,
         'one': 599,
         'reason': 103,
         'oppose': 10,
         'strictly': 4,
         'partisan': 45,
         'political': 169,
         'act': 131,
         'attempts': 5,
         'n': 30,
         'kayleighmcenany': 9,
         'babies': 4,
         'keepamericagreat': 8,
         'shqvujxbir': 1,
         'kayleigh': 1,
         'xom1m2hj23': 1,
         'dow': 32,
         'closes': 5,
         'high': 206,
         'cvpayne': 8,
         'interesting': 41,
         'demanding': 8,
         'fairness': 19,
         'from': 1024,
         'senatemajldr': 49,
         'mcconnell': 42,
         'when': 547,
         'presided': 2,
         'most': 313,
         'unfair': 88,
         'hearing': 64,
         'history': 345,
         'congress': 325,
         'indian': 5,
         'country': 961,
         'such': 176,
         'important': 184,
         'part': 100,
         'story': 212,
         'recently': 31,
         'signed': 89,
         '3': 182,
         'bills': 23,
         'tribal': 2,
         'sovereignty': 5,
         'native': 5,
         'culture': 10,
         '216': 1,
         'spokane': 1,
         'tribe': 3,
         '256': 1,
         'languages': 1,
         'ndaa': 5,
         'sec': 10,
         '2870': 1,
         'officially': 22,
         'recognizing': 4,
         'little': 113,
         'shell': 1,
         'chippewa': 1,
         'indians': 1,
         'my': 1106,
         'honor': 264,
         'stock': 129,
         'market': 159,
         'rally': 114,
         'outpacing': 2,
         'past': 72,
         'presidents': 34,
         'cnbc': 9,
         'trade': 383,
         'deals': 86,
         'speaker': 48,
         'schumer': 90,
         'drive': 11,
         'rig': 5,
         'trial': 36,
         'against': 325,
         'misplaced': 1,
         'there': 829,
         'factual': 2,
         'basis': 23,
         'articles': 20,
         'passed': 45,
         'house': 531,
         'exonerated': 8,
         'william': 7,
         'mcginley': 1,
         'kristy': 1,
         'year': 340,
         'iahxpxnzg7': 1,
         'academy': 6,
         'award': 17,
         'actor': 1,
         'guy': 84,
         'jonvoight': 4,
         'fantastic': 112,
         'role': 14,
         'mickey': 1,
         'donovan': 3,
         'television': 27,
         'hit': 109,
         'ray': 7,
         'midnight': 1,
         'cowboy': 1,
         'deliverance': 1,
         'champ': 3,
         'boxing': 3,
         'movies': 3,
         'many': 742,
         'delivers': 12,
         'also': 329,
         'loves': 117,
         'usa': 219,
         'tombx7m': 1,
         'agreepray': 1,
         'morningjoe': 1,
         'mondaymotivation': 1,
         'mondaythoughts': 1,
         'tcot': 1,
         'kag2020': 26,
         'trump20': 1,
         'charliekirk11': 28,
         'daily': 10,
         'reminder': 19,
         'barack': 16,
         'asked': 99,
         'rival': 5,
         'campaign': 271,
         'manager3': 1,
         'repeatedly': 6,
         'claimed': 9,
         'urgent': 4,
         'matter': 59,
         'uses': 9,
         'stall': 2,
         'tactics': 7,
         'obstruct': 30,
         'senate': 279,
         'replouiegohmert': 10,
         'heytammybruce': 6,
         'foxnews': 302,
         'expose': 8,
         'weakness': 8,
         'greggjarrett': 38,
         'davidjharrisjr': 2,
         'merry': 16,
         'friends': 83,
         'amazing': 94,
         'isupport45': 1,
         'god': 123,
         'xbmctdhgp4': 1,
         'ritchie': 1,
         '1tnvnxrcdn': 1,
         'trumpwarroom': 22,
         'believe': 151,
         'law': 238,
         'abiding': 4,
         'criminal': 81,
         'aliens': 35,
         'open': 143,
         'borders': 160,
         'agen': 1,
         'retirement': 6,
         'savings': 3,
         'under': 224,
         'nasdaq': 16,
         '9000': 4,
         'watch': 199,
         'franklin_graham': 10,
         'says': 99,
         'much': 594,
         'father': 36,
         'billy': 13,
         'graham': 36,
         'whole': 67,
         'lot': 74,
         'people': 1322,
         'delivered': 25,
         'franklin_graha': 1,
         'eve': 7,
         'members': 106,
         'military': 391,
         'stationed': 1,
         'across': 72,
         'mari': 1,
         'farnesitweets': 1,
         'launch': 16,
         'evangelicals': 3,
         'coalition': 10,
         'friday': 24,
         'january': 27,
         'miami': 13,
         'fl': 6,
         'keepameric': 1,
         'azachparkinson': 1,
         'p': 161,
         '500': 32,
         'returned': 29,
         '50': 90,
         'since': 230,
         'elected': 67,
         'double': 23,
         '23': 8,
         'average': 23,
         'return': 22,
         'pres': 27,
         'mchooyah': 1,
         'officers': 40,
         'held': 40,
         'private': 36,
         'meetings': 78,
         'enlisted': 2,
         'troops': 51,
         'candidly': 1,
         'discuss': 36,
         'war': 91,
         'afghanistan': 20,
         'htt': 16,
         'promise': 37,
         'promisesmadepromiseskept': 1,
         '91nq7nfknf': 1,
         'booming': 32,
         'benefiting': 4,
         'higher': 72,
         'wages': 26,
         'job': 454,
         'opportunities': 9,
         'markszaidesq': 1,
         'odnigov': 1,
         'marshablackburn': 7,
         'pretty': 10,
         'simple': 30,
         'cia': 29,
         'real': 171,
         'mediaite': 2,
         'censorship': 8,
         'fox': 72,
         'calls': 45,
         'canadian': 4,
         'broadcaster': 1,
         'removing': 9,
         'alone': 16,
         'k0zivutrcc': 1,
         'movie': 6,
         'kidding': 9,
         'fogquk1ei7': 1,
         'guess': 23,
         'justin': 7,
         'him': 365,
         'pay': 130,
         'nato': 87,
         'or': 793,
         'snds7yvigr': 1,
         'leads': 9,
         'nation': 187,
         'both': 150,
         'number': 102,
         'percentage': 7,
         'increase': 47,
         'population': 6,
         'terrible': 125,

In [10]:
# Reference the file where the CSV is located
tweet_data = "trumpTime.csv"

# Import the data into a Pandas DataFrame
trump_df = pd.read_csv(tweet_data)
trump_df.head()

,Unnamed: 0,Unnamed: 0.1,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,Year,Hour,Day,Month
0,0,0,Twitter for iPhone,Our prayers are with the families of the victi...,12-31-2019 00:57:13,39706,191167,False,1211813523581546496,2019,12 AM to 4 AM,31,12
1,1,1,Twitter for iPhone,RT @realDonaldTrump: https://t.co/Mn4EJ7Jbh8,12-31-2019 00:00:34,40917,0,True,1211799266974478337,2019,12 AM to 4 AM,31,12
2,2,2,Twitter for iPhone,RT @BreitbartNews: This Christmas let the impe...,12-30-2019 22:23:36,6012,0,True,1211774864362737665,2019,8 PM to 12 AM,30,12
3,3,3,Twitter for iPhone,He is Fake News will always be Fredo to us. I ...,12-30-2019 22:23:04,20037,81302,False,1211774730258264066,2019,8 PM to 12 AM,30,12
4,4,4,Twitter for iPhone,Thank you to highly respected Jewish leader Do...,12-30-2019 14:28:26,21588,112303,False,1211655287247126535,2019,12 PM to 4 PM,30,12

In [14]:
trump_df["Daily"] = trump_df['Month'].str.cat(trump_df['Day'],sep=" ")

AttributeError: Can only use .str accessor with string values!

In [13]:
trump_df.head()

,Unnamed: 0,Unnamed: 0.1,source,text,created_at,retweet_count,favorite_count,is_retweet,id_str,Year,Hour,Day,Month,Daily
0,0,0,Twitter for iPhone,Our prayers are with the families of the victi...,12-31-2019 00:57:13,39706,191167,False,1211813523581546496,2019,12 AM to 4 AM,31,12,43
1,1,1,Twitter for iPhone,RT @realDonaldTrump: https://t.co/Mn4EJ7Jbh8,12-31-2019 00:00:34,40917,0,True,1211799266974478337,2019,12 AM to 4 AM,31,12,43
2,2,2,Twitter for iPhone,RT @BreitbartNews: This Christmas let the impe...,12-30-2019 22:23:36,6012,0,True,1211774864362737665,2019,8 PM to 12 AM,30,12,42
3,3,3,Twitter for iPhone,He is Fake News will always be Fredo to us. I ...,12-30-2019 22:23:04,20037,81302,False,1211774730258264066,2019,8 PM to 12 AM,30,12,42
4,4,4,Twitter for iPhone,Thank you to highly respected Jewish leader Do...,12-30-2019 14:28:26,21588,112303,False,1211655287247126535,2019,12 PM to 4 PM,30,12,42

In [46]:
counts.to_csv('tweetcounts.csv')

AttributeError: 'Counter' object has no attribute 'to_csv'

In [2]:
temp_df=trump_df[['text', 'created_at']].copy()

In [3]:
temp_df

                                                    text           created_at
0      Our prayers are with the families of the victi...  12-31-2019 00:57:13
1           RT @realDonaldTrump: https://t.co/Mn4EJ7Jbh8  12-31-2019 00:00:34
2      RT @BreitbartNews: This Christmas let the impe...  12-30-2019 22:23:36
3      He is Fake News will always be Fredo to us. I ...  12-30-2019 22:23:04
4      Thank you to highly respected Jewish leader Do...  12-30-2019 14:28:26
...                                                  ...                  ...
13866  @CNN just released a book called "Unprecedente...  01-02-2017 18:32:29
13867  Chicago murder rate is record setting - 4331 s...  01-02-2017 17:31:17
13868  Well the New Year begins. We will together MAK...  01-02-2017 14:40:10
13869  RT @IvankaTrump: 2016 has been one of the most...  01-01-2017 06:49:49
13870  RT @DonaldJTrumpJr: Happy new year everyone. #...  01-01-2017 06:49:33

[13871 rows x 2 columns]

In [4]:
temp_df['created_at'] = pd.to_datetime(temp_df.created_at)

In [5]:
temp_df['new_time'] = temp_df['created_at'].dt.strftime('%Y%m%d')

In [6]:
temp_df

,text,created_at,new_time
0,Our prayers are with the families of the victi...,2019-12-31 00:57:13,20191231
1,RT @realDonaldTrump: https://t.co/Mn4EJ7Jbh8,2019-12-31 00:00:34,20191231
2,RT @BreitbartNews: This Christmas let the impe...,2019-12-30 22:23:36,20191230
3,He is Fake News will always be Fredo to us. I ...,2019-12-30 22:23:04,20191230
4,Thank you to highly respected Jewish leader Do...,2019-12-30 14:28:26,20191230
...,...,...,...
13866,"@CNN just released a book called ""Unprecedente...",2017-01-02 18:32:29,20170102
13867,Chicago murder rate is record setting - 4331 s...,2017-01-02 17:31:17,20170102
13868,Well the New Year begins. We will together MAK...,2017-01-02 14:40:10,20170102
13869,RT @IvankaTrump: 2016 has been one of the most...,2017-01-01 06:49:49,20170101
13870,RT @DonaldJTrumpJr: Happy new year everyone. #...,2017-01-01 06:49:33,20170101

In [7]:
us = ["us", "republicans", "we", "our", "i", "me", "my", "republican", "gop", "right", "i'm", "conservative", "conservatives"]
them = ["they", "them", "dems", "democrats", "failing", "schumer", "pelosi", "left", "democratic", "radical", "libs", "liberal", "liberals"]

In [11]:
duuh=[]

for index, row in temp_df.iterrows():
    countforus=0
    countforthem= 0
    result={}
    
    stringe = row['text'].lower().split(" ")
    for word in stringe:
        if word in us:
            countforus+= 1
        elif word in them:
            countforthem +=1
    
    result["Date"]= row["new_time"]
    result["Them"]= countforthem
    result["Us"]=countforus
    duuh.append(result)

In [12]:
duuh[0]

{'Date': '20191231', 'Them': 1, 'Us': 1}

In [18]:
temp_df['new_time'] = pd.DataFrame({'created_at':pd.date_range('01-01-2017', periods = 60, freq='D')})

temp_df.created_at.dt.strftime('%Y%m%d').astype(int)

0        20191231
1        20191231
2        20191230
3        20191230
4        20191230
           ...
13866    20170102
13867    20170102
13868    20170102
13869    20170101
13870    20170101
Name: created_at, Length: 13871, dtype: int32

In [13]:
Us_Them_df=pd.DataFrame(duuh)

In [14]:
Us_Them_df.head()

       Date  Them  Us
0  20191231     1   1
1  20191231     0   0
2  20191230     1   0
3  20191230     0   1
4  20191230     0   1

In [15]:
totals_df= Us_Them_df.groupby(['Date'])

In [19]:
totals_df.sum()

          Them  Us
Date
20170101     0   2
20170102     2   5
20170103     1   1
20170104     7   1
20170105     4   5
...        ...  ..
20191227     3   7
20191228    14  17
20191229     2   2
20191230     1   2
20191231     1   1

[1082 rows x 2 columns]

In [9]:
import datetime
from dateutil.relativedelta import relativedelta
from datetime import date

temp_df['new_time']=temp_df['created_at'].strftime('%Y%m%d')

AttributeError: 'Series' object has no attribute 'strftime'

In [1]:
us = ["us", "republicans", "we", "our", "i", "me", "my", "republican", "gop", "right", "i'm", "conservative", "conservatives"]
them = ["they", "them", "dems", "democrats", "failing", "schumer", "pelosi", "left", "democratic", "radical", "libs", "liberal", "liberals"]

In [2]:
# create text searches and match column
temp_df["Text_search"] = us.str.lower().str.split()
temp_df["result"] = df.apply(search_func, axis=1)

# show result
print(temp_df)



#for sentence in my_list:
#    counts.update(words.findall(sentence.lower()))

AttributeError: 'list' object has no attribute 'str'

In [25]:
us = ["us", "republicans", "we", "our", "i", "me", "my", "republican", "gop", "right", "i'm", "conservative", "conservatives"]
df = pd.DataFrame()
temp_df["text"]=[word.lower() for word in us] # you won't need this bc they are all lowercase anyway

def search_row(word, text):
    return text.lower().count(word.lower())

example = "here is a really long string of random stuf ... asdf as alwek naskdf n republican, repucliban republican I'm"

df["result"]=df.apply(lambda row: search_row(row["text"], temp_df[2]), axis=1)



us = ["us", "republicans", "we", "our", "i", "me", "my", "republican", "gop", "right", "i'm", "conservative", "conservatives"]
df = pd.DataFrame()
df["Text_search"]=[word.lower() for word in us] # you won't need this bc they are all lowercase anyway

def search_row(word, text):
   return text.lower().count(word.lower())

 example = "here is a really long string of random stuf ... asdf as alwek naskdf n republican, repucliban republican I'm"

df["result"]=df.apply(lambda row: search_row(row["Text_search"], example), axis=1)

ValueError: Length of values does not match length of index

In [24]:
df

      Text_search  result
0              us       0
1     republicans       0
2              we       1
3             our       0
4               i       6
5              me       0
6              my       0
7      republican       2
8             gop       0
9           right       0
10            i'm       1
11   conservative       0
12  conservatives       0


counter

In [42]:
csv_file = "counts.csv"
csv_columns = ['word', 'count']
try:
    with open(csv_file, 'w') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=csv_columns)
        writer.writeheader()
        for data in counts:
            writer.writerow(data)
except IOError:
    print("I/O error")

AttributeError: 'str' object has no attribute 'keys'